wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.13
    framework: tensorflow
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.6.8
    t:
      1:
      - 3
      - 5
      4: 3.6.8
      5: 0.10.13
      8:
      - 1
